### ISSUE TITLE
Craft Image Transforms in Gatsby

### ISSUE THREAD

**Issue by mcclaskiem** [craftcms/gatsby-source-craft#16]
### Description

I have tried every combo that is outlined by the documentation to get Image transforms to work and nothing seems to be working:

**Option 1:**
When I add my own directory for `fragments` with a test image transform, it causes the entire Craft schema to not work. Gatsby is not able to find ANY of the types that the source plugin usually provides. I have also tried both fragment types inside of my `.graphql` file:

```
fragment resizedImage on Craft_projectSlide_BlockType {
  featuredImage {
    resized: url @transform(width: 1400)
  }
}
```

```
fragment Craft_digitalOcean_Asset on Craft_digitalOcean_Asset {
  frontPageThumb: url(width: 400, height: 400)
}
```

**Option 2:**
Added the transform directive along side my other fragments inside a component. Gatsby errors saying that the directive does not exist.

**Option 3:**
I tried adding the transform field directly to the `digitalOcean_Asset` type inside of a component also does not work. When trying this it throws an error that `url` does not have an argument `width` or any of the other possible arguments.

### Steps to reproduce

1. Updated the `fragmentsDir` option and observe no Craft types available
2.

### Additional info
The `craft-fragments` folder inside of the `.cache` of `node_modules` is empty after sourcing.

As a test I went into the default folder set by the plugin for fragments and added my transform fragment there. When I start up the site the same error occurs as when I add a custom directory for fragment. The entire Craft schema breaks and no types are available within Gatsby GraphQL schema

- Craft version: 3.5.17.1
- PHP version: 7.4
- Database driver & version:
- Plugins & versions: 
"gatsby": "^2.29.3",
"gatsby-source-craft": "^1.0.0-beta.2",
"gatsby-source-graphql": "^2.5.3",

**Comment by mcclaskiem** [comment]
After some more digging, it seems like the file path is not the issue but more so an issue with Parent Types in the GQL schema. Below is the fragment I am trying to apply and the resulting error which ends up causing a breakdown before any other schemas are written.

```
fragment resizedImage on Craft_projects_projects_Entry {
  image {
    resizedHero: url @transform (width: 300 height: 300)
  }
}
```


```
Error:
Field "image" at path "resizedImage" has no parent type. This may indicate that your remote schema had changed and your fragment "resizedImage" must be updated.
```

Is the fragment getting applied before assets or other types are generated?

**Comment by andris-sevcenko** [comment]
It sounds as if you're confusing the stages of building a Gatsby site.

A Gatsby site build happens in three steps:
**Sourcing**: Data is sourced from Craft by talking to Craft GraphQL API directly.
**Internalizing**: Said data is parsed by Gatsby and the internal Gatsby data store is built
**Building**: Site is built by querying the Gatsby data store.

The following are important characteristics for each step (as it pertains to your problem):

### Sourcing
- This is the only step where Craft server-side actions (transforms, for example) are possible
- Custom fragments are injected at this step
- Since we're talking to Craft directly, the `typePrefix` setting does not apply

### Internalizing datastore
- Since it's possible data comes in from multiple sources and there's a conflict possible, this is the step where `typePrefix` setting is applied to prevent that.

### Building the site
- All the GraphQL queries are directed towards Gatsby's data store. Additional fetching of data or filtering data that you would commonly use in Craft Twig templates is no longer available.
- All the transforms are unavailable, too.
- If you wanted additional data, you should have added custom fragments for it.

So, keeping all of that in mind, I think you've confused some parts of sourcing with some parts of building.

The solution is simple - if I'm understanding everything correctly, you should use the following fragment:

```graphql
fragment resizedImage on projectSlide_BlockType {
  featuredImage {
    resized: url @transform(width: 1400)
  }
}
```

Let me know how that goes!

**Comment by mcclaskiem** [comment]
@andris-sevcenko You are totally right! I actually figured this out late last night and didn't have time to update this thread. I was following the same fragment structure that I used in components which as you stated includes the `typePrefix` property to prevent claching. I am all set now!
